---

computername: Kerngehäuse
hostname: kerngehaeuse

finder_proxy_icon_hover_delay: 0

safari_show_full_url_in_address_bar: true
safari_open_safe_files_automatically: true
safari_show_status_bar: true
safari_show_developer_menu: true

system_save_application_state_on_quit: yes
system_expand_save_panel_by_default: yes
system_expand_print_panel_by_default: yes
system_show_file_extensions_warning: no
system_warn_before_emptying_the_trash: yes
system_use_f_keys_as_standard_function_keys: no
trackpad_tap_to_click: yes

screensaver_ask_for_password: no
screensaver_ask_for_password_in_seconds: 5

shell_path: /usr/local/bin/zsh

mas_upgrade_all_apps: yes
update_homebrew: yes

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-fonts
  - jeromegamez/formulae
  - github/gh
  - aws/tap

homebrew_apps:
  - firefox
  - gpg-suite
  - google-chrome
  - keepassxc
  - meld
  - rectangle
  - spotify
  - telegram
  - tunnelblick
  - visual-studio-code
  - whatsapp

homebrew_packages:
  - curl
  - git
  - jq
  - make
  - python
  - warrensbox/tap/tfswitch
  - vim
  - wget
  - zlib
  - zsh

mas_apps:
  - { name: Keynote, id: 409183694 }
  - { name: iMovie, id: 408981434 }
  - { name: Pages, id: 409201541 }
  - { name: GarageBand, id: 682658836 }
  - { name: Numbers, id: 409203825 }
